# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xci
# IP: The module: 'pxl_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xci
# IP: The module: 'pxl_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/EE478 LAB5/project/LAB5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pxl_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
