# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen.xci
# IP: The module: 'mclk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen.xci
# IP: The module: 'mclk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/EE478 LAB4/LAB4/LAB4.srcs/sources_1/ip/mclk_gen_1/mclk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mclk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
